version: '3.5'

services:
  ukrtrackingbotapiwrappernovaposhta:
    image: my.registry/trackingbot/ukrtrackingbotapiwrappernovaposhta{tag}
    build:
      context: ./UkrTrackingBot.ApiWrapper.NovaPoshta
      dockerfile: Dockerfile
    environment:
      - Exceptionless:ApiKey=exceptionlessapikey
      - MongoDbLogging:MongoDb=database
      - MongoDbLogging:MongoPassword=databasepassword
      - MongoDbLogging:MongoDbAddress=dbaddress
      - API_KEY novaposhtaapikey
  ukrtrackingbotapiwrapperdeliveryauto:
    image: my.registry/trackingbot/ukrtrackingbotapiwrapperdeliveryauto{tag}
    build:
      context: ./UkrTrackingBot.ApiWrapper.DeliveryAuto
      dockerfile: Dockerfile
    environment:
      - Exceptionless:ApiKey=exceptionlessapikey
      - MongoDbLogging:MongoDb=database
      - MongoDbLogging:MongoPassword=databasepassword
      - MongoDbLogging:MongoDbAddress=dbaddress
      - API_KEY deliveryapikey
  redismaster:
    image: redis:3
  redisslave:
    image: redis:3
    command: redis-server --slaveof redismaster 6379
    links:
      - redismaster
  sentinel:
    image: my.registry/trackingbot/sentinel{tag}
    build: redis-sentinel
    environment:
      - SENTINEL_DOWN_AFTER=5000
      - SENTINEL_FAILOVER=5000    
    links:
      - redismaster
      - redisslave
  ukrtrackingbottelegramconsole:
    image: my.registry/trackingbot/ukrtrackingbottelegramconsole{tag}
    build:
      context: ./UkrTrackingBot.Telegram.Console
      dockerfile: Dockerfile
    links:
      - ukrtrackingbotapiwrappernovaposhta
      - ukrtrackingbotapiwrapperdeliveryauto
      - redismaster
    environment:
      - NP_ADDRESS=http://ukrtrackingbotapiwrappernovaposhta:80
      - DEL_ADDRESS=http://ukrtrackingbotapiwrapperdeliveryauto:80
      - REDIS_ADDRESS=redismaster:6379
      - BOT_TOKEN=token
      - Exceptionless:ApiKey=exceptionlessapikey
      - MongoDbLogging:MongoDb=database
      - MongoDbLogging:MongoPassword=databasepassword
      - MongoDbLogging:MongoDbAddress=dbaddress
  ukrtrackingbottelegramweb:
    image: my.registry/trackingbot/ukrtrackingbottelegramweb{tag}
    build:
      context: ./UkrTrackingBot.Telegram.Web
      dockerfile: Dockerfile
    links:
      - ukrtrackingbotapiwrappernovaposhta
      - ukrtrackingbotapiwrapperdeliveryauto
      - redismaster
    environment:
      - NP_ADDRESS=http://ukrtrackingbotapiwrappernovaposhta:80
      - DEL_ADDRESS=http://ukrtrackingbotapiwrapperdeliveryauto:80
      - REDIS_ADDRESS=redismaster:6379
      - BOT_TOKEN=token
      - Exceptionless:ApiKey=exceptionlessapikey
      - MongoDbLogging:MongoDb=database
      - MongoDbLogging:MongoPassword=databasepassword
      - MongoDbLogging:MongoDbAddress=dbaddress
  ukrtrackingbotidentityserver:
    image: my.registry/trackingbot/ukrtrackingbotidentityserver{tag}
    build:
      context: ./UkrTrackingBot.IdentityServer
      dockerfile: Dockerfile
    environment:
      - Exceptionless:ApiKey=exceptionlessapikey
      - MongoDbLogging:MongoDb=database
      - MongoDbLogging:MongoPassword=databasepassword
      - MongoDbLogging:MongoDbAddress=dbaddress
      - MVC_REDIRECT_URI=redirectUri
      - MVC_POST_LOGOUT_REDIRECT_URI=logoutRedirectUri
      - SIGN_CERT_PASSWORD=pwd
  ukrtrackingbotweb:
    image: my.registry/trackingbot/ukrtrackingbotweb{tag}
    build:
      context: ./UkrTrackingBot.Web
      dockerfile: Dockerfile
    environment:
      - Exceptionless:ApiKey=exceptionlessapikey
      - MongoDbLogging:MongoDb=database
      - MongoDbLogging:MongoPassword=databasepassword
      - MongoDbLogging:MongoDbAddress=dbaddress
      - IDENTITYSERVER_AUTHORITYURL=authorityUrl
  nginxproxy:
    image: my.registry/trackingbot/nginxproxy{tag}
    build:
      context:  ./nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - type: volume
        source: nginx_etc
        target: /etc/letsencrypt
        volume:
          nocopy: true

volumes:
  nginx_etc: